kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: cachet
spec:
  lookupPolicy:
    local: false
  tags:
    - name: stable
      annotations: null
      from:
        kind: DockerImage
        name: 'docker.io/cachethq/docker:2.3.18'
      generation: 3
      importPolicy: {}
      referencePolicy:
        type: Source
