kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: cachet
spec:
  lookupPolicy:
    local: false
  tags:
    - name: stable
      from:
        kind: DockerImage
        name: 'quay.io/vrutkovs/cachet:devel'
      importPolicy: {}
      referencePolicy:
        type: Source
