apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: cachet-routing
spec:
  route:
    receiver: cachet
    groupBy: [alertname]
    groupWait: 30s
    groupInterval: 1m
    repeatInterval: 1h
  receivers:
  - name: cachet
    webhookConfigs:
    - url: "http://prometheus-cachet:8080/webhook"
