kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: prometheus-cachet
  labels:
    app: prometheus-cachet
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - prometheus-cachet
        from:
          kind: ImageStreamTag
          namespace: cachet-dev
          name: 'prometheus-cachet:latest'
    - type: ConfigChange
  replicas: 1
  revisionHistoryLimit: 10
  test: false
  selector:
    app: prometheus-cachet
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prometheus-cachet
    spec:
      containers:
        - name: prometheus-cachet
          image: ' '
          env:
            - name: PORT
              value: '8080'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
