apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cachet
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  sourceRepos:
    - '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
    - namespace: cachet
      server: https://kubernetes.default.svc
    - namespace: cachet-prometheus
      server: https://kubernetes.default.svc
