apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cachet
  namespace: openshift-gitops
spec:
  destination:
    namespace: cachet
    server: 'https://kubernetes.default.svc'
  project: cachet
  source:
    path: apps/cachet
    repoURL: 'https://github.com/vrutkovs/okd-status-page'
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
  - group: apps
    kind: Deployment
    name: cachet
    jsonPointers:
    - /spec/template/spec/containers/0/image
  - group: apps.openshift.io
    kind: DeploymentConfig
    name: postgresql
    jsonPointers:
    - /spec/template/spec/containers/0/image
  - group: apps.openshift.io
    kind: DeploymentConfig
    name: prometheus-cachet
    jsonPointers:
    - /spec/template/spec/containers/0/image
